# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_MVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo_MVVM
pod 'Alamofire','~> 4.7.0'
pod 'SwiftyJSON','~> 4.0.0'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'

end
